swagger: "2.0"

info:
  title: "Hello World API"
  version: "1.0"

paths:
  /hello:
    get:
      summary: Prints all the keys
      operationId: app.print_keys
      responses:
        200:
          description: All keys are printed
          schema:
            type: string
          examples:
            "text/html": "Hello World"
    put:
      summary: Post version of hello world
      operationId: app.add_key
      parameters:
        - name: key
          in: body
          required: true
          schema:
            $ref: '#/definitions/Key'
      responses:
        200:
          description: creates a key/value
  /hello/{name}:
    get:
      summary: Returns name and value for the given key
      operationId: app.get_key
      parameters:
        - name: name
          in: path
          required: true
          type: string
      responses:
        200:
          description: Finds a key
          schema:
            $ref: '#/definitions/Key'
        404:
          description: Key does not exist

definitions:
  Key:
    type: object
    required:
      - name
      - value
    properties:
      name:
        type: string
        description: name of the key
        readOnly: true
      value:
        type: string
        description:  value of the key
