swagger: "2.0"

info:
  title: "Hello World API"
  version: "1.0"

paths:
  /hello:
    get:
      summary: Just prints "Hello World"
      operationId: app.my_form
      produces:
        - text/html;
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/html": "Hello World"
    post:
      summary: Post version of hello world
      operationId: app.my_form_post
      produces:
        - text/plain;
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello World"
