swagger: "2.0"

info:
  title: "Hello World API"
  version: "1.0"

paths:
  /:
    get:
      summary: Just prints "Hello World"
      operationId: app.get_world
      produces:
        - text/plain;
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello World"
    post:
      summary: Post version of hello world
      operationId: app.post_world
      produces:
        - text/plain;
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello World"
